name: Get GitHub App Token
author: "AB INNOVISION GmbH"
description: |
  Gets the token for the GitHub App based on the given identification.
inputs:
  identification:
    description: "Identification value of the GitHub App. Secret: 'GH_APP_IDENTIFICATION_<UPPERCASE APP NAME>'"
    required: true
outputs:
  token:
    description: ""
    value: ${{ steps.token.outputs.token }}
  app-commiter-email:
    description: ""
    value: ${{ steps.get-details.outputs.committer-email }}
  app-commiter-name:
    description: ""
    value: ${{ steps.get-details.outputs.committer-name }}
runs:
  using: composite
  steps:
    - id: prepare
      name: "Prepare"
      shell: bash
      run: |
        DECODED=$(echo "${{ inputs.identification }}" | base64 --decode)
        echo "APP_ID=$(echo "$DECODED" | jq -cr ".id")" >> $GITHUB_ENV
        echo "APP_CERTIFICATE=$(echo "$DECODED" | jq -cr ".certificate")" >> $GITHUB_ENV
    - id: secrets
      name: "Load secrets"
      uses: google-github-actions/get-secretmanager-secrets@v1.0.0
      with:
        secrets: |-
          id:${{ env.APP_ID }}
          certificate:${{ env.APP_CERTIFICATE }}
    - id: token
      name: "Generate token"
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ steps.secrets.outputs.id }}
        private-key: ${{ steps.secrets.outputs.certificate }}
    - id: get-details
      env:
        GH_TOKEN: ${{ steps.app-token.outputs.token }}
      shell: bash
      run: |
        # Fetch the id of the bot user.
        response=$(gh api "/users/${{ steps.token.outputs.app-slug }}[bot]") >> "$GITHUB_OUTPUT"

        # Extract the id of the bot user.
        user_id=$(echo "$response" | jq -cr ".id")

        echo "committer-email=${{ steps.token.outputs.app-slug }}[bot] <$user_id+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com>" >> "$GITHUB_OUTPUT"
        echo "committer-name=${{ steps.token.outputs.app-slug }}[bot]" >> "$GITHUB_OUTPUT"
