# This workflow is used to release any repository using release-please.

name: Release

on:
  workflow_call:
    secrets:
      GH_APP_IDENTIFICATION_RELEASER:
        required: true
    inputs:
      gcp-auth:
        type: string
        required: false
        default: ${{ vars.GCP_AUTH }}
      target-branch:
        type: string
        required: false
        default: ""
        description: |-
          Branch to release from. Defaults to the repository default branch.
      prerelease-channel:
        type: string
        required: false
        default: ""
        description: |-
          Prerelease channel name (e.g., "beta", "canary", "rc").
          When set, computes prerelease versions for packages with pending changes.
          Format: {next-version}-{channel}.{commit-count}+{short-sha}
          Example: 1.4.0-beta.5+a3f2c1d
    outputs:
      versions:
        value: ${{ jobs.release.outputs.versions }}
        description: |-
          JSON object mapping released package paths to version info.
          Each entry contains "version" (semver), "tag" (docker-compatible), and "type" ("release" or "prerelease").
          Populated for both stable releases and prereleases.
          Empty object {} when nothing was released or computed.
          Stable example: {"actions/setup-node": {"version": "1.2.0", "tag": "1.2.0", "type": "release"}}
          Prerelease example: {"actions/setup-node": {"version": "1.3.0-beta.5+a3f2c1d", "tag": "1.3.0-beta.5-a3f2c1d", "type": "prerelease"}}

jobs:
  release:
    name: release-please
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    outputs:
      versions: ${{ steps.release.outputs.versions }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
      - name: Setup GCP Authentication
        uses: abinnovision/actions@setup-gcp-v1
        with:
          auth: ${{ inputs.gcp-auth }}
      - id: token
        name: Generate GitHub App token
        uses: abinnovision/actions@get-github-app-token-v1
        with:
          identification: ${{ secrets.GH_APP_IDENTIFICATION_RELEASER }}
      - id: release
        name: Run release-please
        uses: ./actions/run-release-please
        with:
          token: ${{ steps.token.outputs.token }}
          prerelease-channel: ${{ inputs.prerelease-channel }}
          target-branch: ${{ inputs.target-branch }}
