name: Get GitHub App Token
author: "AB innovision UG"
description: ""

inputs:
  name:
    description: Name of the GitHub App to get the token for.
    required: true
outputs:
  access_token:
    description: ""
    value: ${{ steps.token.outputs.token }}
runs:
  using: composite
  steps:
    - id: secrets
      name: "Load secrets"
      uses: google-github-actions/get-secretmanager-secrets@v1.0.0
      with:
        secrets: |-
          id:abi-provisioning/github-app-id-${{ inputs.name }}
          certificate:abi-provisioning/github-app-certificate-${{ inputs.name }}
    - id: token
      name: "Generate token"
      uses: tibdex/github-app-token@v1
      with:
        app_id: ${{ steps.secrets.outputs.id }}
        private_key: ${{ steps.secrets.outputs.certificate }}
