# Contains different utility checks for Pull Requests.
name: PR Utils

# Only apply to PRs which target 'master' branch.
on:
  pull_request:
    branches:
      - master

jobs:
  lint-commits:
    name: Lint commits
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run linter
        uses: ./packages/run-commitlint
